#!/bin/bash

function git_clone() {
    for repo in $@; do
        if [ ! -d "$(dirname $repo)" ]; then
            git clone https://github.com/$repo
        fi
    done
}

ORIG_DIR="$(pwd)"
PROFILE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# make profile symlinks
ln -sf $PROFILE_DIR/bash/login ~/.bash_profile
ln -sf $PROFILE_DIR/fonts      ~/.fonts
ln -sf $PROFILE_DIR/git/config ~/.gitconfig
ln -sf $PROFILE_DIR/inputrc    ~/.inputrc
ln -sf $PROFILE_DIR/vim/vimrc  ~/.vimrc

# install gnome terminal color scheme
gconftool-2 --load $PROFILE_DIR/gnome-terminal-conf.xml

git config --global core.excludesfile $PROFILE_DIR/git/ignore

mkdir -p $PROFILE_DIR/git/template/hooks

for hook in $(ls $PROFILE_DIR/git/hooks)
do
	ln -s $PROFILE_DIR/git/hooks/$hook $PROFILE_DIR/git/template/hooks/$hook
done

# install vim plugins
cd $PROFILE_DIR/vim/runtime
mkdir -p tmp src
cd src

git_clone                           \
    jlanzarotta/bufexplorer.git     \
     scrooloose/nerdtree.git        \
          tpope/vim-commentary.git  \
     scrooloose/syntastic.git       \
       airblade/vim-gitgutter.git   \
       ctrlpvim/ctrlp.vim.git       \
    vim-airline/vim-airline.git     \
    vim-airline/vim-airline-themes  \
      godlygeek/tabular             \
          tpope/vim-fugitive

$PROFILE_DIR/bin/pload
cd $PROFILE_DIR
git init
cd $ORIG_DIR
