set nocompatible
filetype off

set rtp+=$PROFILE_DIR/vim/bundle/Vundle.vim
call vundle#begin("$PROFILE_DIR/vim/runtime")
Plugin 'VundleVim/Vundle.vim'
Plugin 'airblade/vim-gitgutter'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'godlygeek/tabular'
Plugin 'jlanzarotta/bufexplorer'
Plugin 'scrooloose/nerdtree'
Plugin 'scrooloose/syntastic'
Plugin 'tpope/vim-commentary'
Plugin 'tpope/vim-fugitive'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'majutsushi/tagbar'
Plugin 'pangloss/vim-javascript'
Plugin 'fatih/vim-go'
Plugin 'udalov/kotlin-vim'
call vundle#end()

if exists('airline#*')
    source $PROFILE_DIR/vim/cfg/general.vim
    source $PROFILE_DIR/vim/cfg/mappings.vim
    source $PROFILE_DIR/vim/cfg/plugins.vim
    source $PROFILE_DIR/vim/cfg/functions.vim
endif
