#!/bin/bash

alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

alias g='git'
alias svim='sudo vim'
alias scat='sudo cat'
alias stail='sudo tail'
alias shead='sudo head'

alias pload='source $PROFILE_DIR/bash/login'
alias plist='ls $PROFILE_DIR/bin'
alias pdir='cd $PROFILE_DIR'
