#!/bin/bash

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias ls='ls --color=auto'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

alias svim='sudo -E vim'
alias scat='sudo -E cat'
alias stail='sudo -E tail'
alias shead='sudo -E head'
alias smkdir='sudo -E mkdir'
alias srm='sudo -E rm'

alias g='git'

alias plist='ls $PROFILE_DIR/bin'
alias pdir='cd $PROFILE_DIR'

alias odir='nautilus .'
