#!/bin/bash
# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

# resolve $SOURCE until the file is no longer a symlink
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
    DIR="$( cd -P "$(dirname "$SOURCE")" && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done

# Important! used by profile scripts
export PROFILE_DIR="$( cd -P "$(dirname "$SOURCE")/.." && pwd )"

# if running bash
if [ -n "$BASH_VERSION" ]; then
     "$PROFILE_DIR/bash/bashrc"
fi

PATH="$PROFILE_DIR/bin:$PATH"
